AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  PosttransmissionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: transmissions/transmissionpost/
      Handler: transmissionpost.lambda_handler
      Runtime: python3.7
      Events:
        intellidataTransmissionAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /intellidataTransmissionAPI
            Method: post
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:dynamodb:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':table/intellidataTransmissionTable'


  GettransmissionFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: transmissions/transmissionget/
        Handler: transmissionget.lambda_handler
        Runtime: python3.7
        Events:
          intellidataTransmissionAPI:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /intellidataTransmissionAPI/latest
              Method: get
        Policies:
                - Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action:
                        - 'dynamodb:GetItem'
                        - 'dynamodb:Query'
                      Resource:
                        'Fn::Join':
                          - ''
                          - - 'arn:aws:dynamodb:'
                            - Ref: 'AWS::Region'
                            - ':'
                            - Ref: 'AWS::AccountId'
                            - ':table/intellidataTransmissionTable'

  RefreshtransmissionFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
          CodeUri: transmissions/refreshtransmission/
          Handler: refreshtransmission.lambda_handler
          Runtime: python3.7
          Events:
            intellidataTransmissionAPI:
              Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
              Properties:
                Path: /intellidataTransmissionAPI/refresh
                Method: get
          Policies:
                  - Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'dynamodb:GetItem'
                          - 'dynamodb:Query'
                        Resource:
                          'Fn::Join':
                            - ''
                            - - 'arn:aws:dynamodb:'
                              - Ref: 'AWS::Region'
                              - ':'
                              - Ref: 'AWS::AccountId'
                              - ':table/intellidataTransmissionTable'

  GettransmissionHistoryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: transmissions/transmissiongethistory/
      Handler: transmissiongethistory.lambda_handler
      Runtime: python3.7
      Events:
        intellidataTransmissionAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /intellidataTransmissionAPI/history
            Method: get
      Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'dynamodb:GetItem'
                      - 'dynamodb:Query'
                    Resource:
                      'Fn::Join':
                        - ''
                        - - 'arn:aws:dynamodb:'
                          - Ref: 'AWS::Region'
                          - ':'
                          - Ref: 'AWS::AccountId'
                          - ':table/intellidataTransmissionTable'


  BulkPosttransmissionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: transmissions/bulktransmissionpost/
      Handler: bulktransmissionpost.lambda_handler
      Runtime: python3.7
      Events:
        intellidataTransmissionAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /intellidataTransmissionAPI/upload
            Method: post
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:dynamodb:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':table/intellidataTransmissionTable'


  intellidataTransmissionTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: intellidataTransmissionTable
      AttributeDefinitions:
        - AttributeName: TRANSMISSION_ID
          AttributeType: S
        - AttributeName: ITEM_ID
          AttributeType: N
      KeySchema:
        - AttributeName: TRANSMISSION_ID
          KeyType: HASH
        - AttributeName: ITEM_ID
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  intellidataTransmissionAPI:
    Description: "API Gateway endpoint URL for Prod stage for nrt_post function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/mem/intellidataTransmissionAPI/"
  PosttransmissionFunction:
    Description: "NRT Post Lambda Function ARN"
    Value: !GetAtt PosttransmissionFunction.Arn
  PosttransmissionFunctionIamRole:
    Description: "Implicit IAM Role created for NRT Post function"
    Value: !GetAtt PosttransmissionFunctionRole.Arn
  GettransmissionFunction:
    Description: "NRT Get Lambda Function ARN"
    Value: !GetAtt GettransmissionFunction.Arn
  GettransmissionFunctionIamRole:
    Description: "Implicit IAM Role created for NRT Get function"
    Value: !GetAtt GettransmissionFunctionRole.Arn
  intellidataTransmissionTable:
    Description: "DynamoDB table ARN"
    Value: !GetAtt intellidataTransmissionTable.Arn
