AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 180
Resources:
  PostProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://intellidatastatic/ac3aab445e3bc6d9d0c8d23f5916d409
      Handler: productpost.lambda_handler
      Runtime: python3.7
      Events:
        intellidataProductAPI:
          Type: Api
          Properties:
            Path: /intellidataProductAPI
            Method: post
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/intellidataProductTable
  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://intellidatastatic/b28c1107fda7292c43e4c81307b1ff84
      Handler: productget.lambda_handler
      Runtime: python3.7
      Events:
        intellidataProductAPI:
          Type: Api
          Properties:
            Path: /intellidataProductAPI/latest
            Method: get
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Query
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/intellidataProductTable
  RefreshProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://intellidatastatic/e97599bd0fa067bb63966bec9ac9f735
      Handler: refreshproduct.lambda_handler
      Runtime: python3.7
      Events:
        intellidataProductAPI:
          Type: Api
          Properties:
            Path: /intellidataProductAPI/refresh
            Method: get
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Query
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/intellidataProductTable
  GetProductHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://intellidatastatic/4f3e6aded0fb8ca6af867ba87e1cb7ce
      Handler: productgethistory.lambda_handler
      Runtime: python3.7
      Events:
        intellidataProductAPI:
          Type: Api
          Properties:
            Path: /intellidataProductAPI/history
            Method: get
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Query
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/intellidataProductTable
  BulkPostProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://intellidatastatic/9d1b3371f7f4ad71eb92876ed9397c35
      Handler: bulkproductpost.lambda_handler
      Runtime: python3.7
      Events:
        intellidataProductAPI:
          Type: Api
          Properties:
            Path: /intellidataProductAPI/upload
            Method: post
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/intellidataProductTable
  intellidataProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: intellidataProductTable
      AttributeDefinitions:
      - AttributeName: PRODUCT_ID
        AttributeType: S
      - AttributeName: ITEM_ID
        AttributeType: N
      KeySchema:
      - AttributeName: PRODUCT_ID
        KeyType: HASH
      - AttributeName: ITEM_ID
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  intellidataProductAPI:
    Description: API Gateway endpoint URL for Prod stage for nrt_post function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/intellidataProductAPI/
  PostProductFunction:
    Description: NRT Post Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PostProductFunction
      - Arn
  PostProductFunctionIamRole:
    Description: Implicit IAM Role created for NRT Post function
    Value:
      Fn::GetAtt:
      - PostProductFunctionRole
      - Arn
  GetProductFunction:
    Description: NRT Get Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetProductFunction
      - Arn
  GetProductFunctionIamRole:
    Description: Implicit IAM Role created for NRT Get function
    Value:
      Fn::GetAtt:
      - GetProductFunctionRole
      - Arn
  intellidataProductTable:
    Description: DynamoDB table ARN
    Value:
      Fn::GetAtt:
      - intellidataProductTable
      - Arn
