AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  PostmemberFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: members/memberpost/
      Handler: memberpost.lambda_handler
      Runtime: python3.7
      Events:
        intellidataMemberAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /intellidataMemberAPI
            Method: post
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:dynamodb:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':table/intellidataMemberTable'


  GetmemberFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: members/memberget/
        Handler: memberget.lambda_handler
        Runtime: python3.7
        Events:
          intellidataMemberAPI:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /intellidataMemberAPI/latest
              Method: get
        Policies:
                - Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action:
                        - 'dynamodb:GetItem'
                        - 'dynamodb:Query'
                      Resource:
                        'Fn::Join':
                          - ''
                          - - 'arn:aws:dynamodb:'
                            - Ref: 'AWS::Region'
                            - ':'
                            - Ref: 'AWS::AccountId'
                            - ':table/intellidataMemberTable'

  RefreshmemberFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
          CodeUri: members/refreshmember/
          Handler: refreshmember.lambda_handler
          Runtime: python3.7
          Events:
            intellidataMemberAPI:
              Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
              Properties:
                Path: /intellidataMemberAPI/refresh
                Method: get
          Policies:
                  - Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - 'dynamodb:GetItem'
                          - 'dynamodb:Query'
                        Resource:
                          'Fn::Join':
                            - ''
                            - - 'arn:aws:dynamodb:'
                              - Ref: 'AWS::Region'
                              - ':'
                              - Ref: 'AWS::AccountId'
                              - ':table/intellidataMemberTable'

  GetmemberHistoryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: members/membergethistory/
      Handler: membergethistory.lambda_handler
      Runtime: python3.7
      Events:
        intellidataMemberAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /intellidataMemberAPI/history
            Method: get
      Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'dynamodb:GetItem'
                      - 'dynamodb:Query'
                    Resource:
                      'Fn::Join':
                        - ''
                        - - 'arn:aws:dynamodb:'
                          - Ref: 'AWS::Region'
                          - ':'
                          - Ref: 'AWS::AccountId'
                          - ':table/intellidataMemberTable'


  BulkPostmemberFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: members/bulkmemberpost/
      Handler: bulkmemberpost.lambda_handler
      Runtime: python3.7
      Events:
        intellidataMemberAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /intellidataMemberAPI/upload
            Method: post
      Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:dynamodb:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':table/intellidataMemberTable'


  intellidataMemberTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: intellidataMemberTable
      AttributeDefinitions:
        - AttributeName: MEMBER_ID
          AttributeType: S
        - AttributeName: ITEM_ID
          AttributeType: N
      KeySchema:
        - AttributeName: MEMBER_ID
          KeyType: HASH
        - AttributeName: ITEM_ID
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  intellidataMemberAPI:
    Description: "API Gateway endpoint URL for Prod stage for nrt_post function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/mem/intellidataMemberAPI/"
  PostmemberFunction:
    Description: "NRT Post Lambda Function ARN"
    Value: !GetAtt PostmemberFunction.Arn
  PostmemberFunctionIamRole:
    Description: "Implicit IAM Role created for NRT Post function"
    Value: !GetAtt PostmemberFunctionRole.Arn
  GetmemberFunction:
    Description: "NRT Get Lambda Function ARN"
    Value: !GetAtt GetmemberFunction.Arn
  GetmemberFunctionIamRole:
    Description: "Implicit IAM Role created for NRT Get function"
    Value: !GetAtt GetmemberFunctionRole.Arn
  intellidataMemberTable:
    Description: "DynamoDB table ARN"
    Value: !GetAtt intellidataMemberTable.Arn
